Models/Token.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication3.Models
{
    public class Token
    {
        public string Type { get; set; }
        public string Text { get; set; }

        public int LineNum { get; set; }
        public Token()
        {

        }
        public Token(string type, string text)
        {
            this.Type = type;
            this.Text = text;
            this.LineNum = 1;

        }
    }
    }

ViewModels/TokenViews.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication3.ViewModels
{
    public class TokenViews
    {
        public List<string> tok { get; set; }
    }
}

Controllers/TokenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication3.Services;
using WebApplication3.ViewModels;
using Newtonsoft.Json;
namespace WebApplication3.Controllers
{
    public class TokenController : Controller
    {
        Compiler Compiler = new Compiler() ;

       


       [HttpGet]
        public ActionResult SaveRecord()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SaveRecord(String content, HttpPostedFileBase browse)
        {
            if (browse != null)
            {


            string pic = System.IO.Path.GetFileName(browse.FileName);
            string path = System.IO.Path.Combine(Server.MapPath("~/files/"),pic);
            browse.SaveAs(path);
            string sas = "C:\\Users\\Ahmed\\Desktop\\WebApplication3\\WebApplication3\\WebApplication3\\files\\" + pic;
            string s = Compiler.getCodeFromFile(sas);

            var list = Compiler.DisplayTokens(s);
            ViewBag.Emp_data = list;
            }
            else if (content!=null)
            {
                string s = Compiler.getCodeFromFile(content);

                var list = Compiler.DisplayTokens(s);
                ViewBag.Emp_data = list;
            }
            return View();
        }

    }
}

Views/Shared/_Layout.cshtml

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @*<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
        <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button>
        @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div> </div>
        </div>*@
    <div class="container body-content">
        @RenderBody()
    </div> @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>


Views/Token/SaveRecord.cshtml
<head>
    <title>Compiler</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/Content/codemirror-5.65.3/lib/codemirror.css">
    <link rel="stylesheet" href="~/Content/codemirror-5.65.3/theme/darcula.css">
    <script src="~/Content/codemirror-5.65.3/addon/comment/comment.js"></script>
    <script src="~/Content/codemirror-5.65.3/lib/codemirror.js"></script>
    <style>
        body {
            background-color: black;
        }



        .xx {
            float: right;
            width: 300px;
        }





        button,
        label {
            margin: 25px 0;
            color: white;
            font-size: 18px;
        }



        .editor {
            height: 1000px
        }



        .h6 {
            background-color: seagreen;
            padding: 10px;
        }
    </style>
</head>



<body>
    <div validateRequest="false" class="container">
        @using (Html.BeginForm("SaveRecord", "Token", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            <div>
                <label for="file">
                    <input class="browse" id="file" type="file" accept=".txt" name="browse">
                </label>
                <button class="xx btn btn-success" name="scan">Scan</button>
            </div>
<textarea style="height:600px; width:1140px; " name="content" class="editor"></textarea>
        }
        <div style="color:white;">
            <div class="h6">
                @if (ViewBag.Emp_data != null)
                {
                    foreach (var item in ViewBag.Emp_data)
                    {
                        <div>
                            <h6> @item</h6>
                        </div>



                    }
                }
            </div>
        </div>



    </div>



    <script src="~/Scripts/script.js"></script>



    <script>
        input.addEventListener("input", myscript);



        function myscript() {
            // e.preventDefualt;



            console.log("asda");
        }
        let editor = CodeMirror.fromTextArea(
            document.getElementById("editor"), {
                // theme: "darcula",
                lineNumbers: true,
            });
        input.addEventListener("input", myscript);



        function myscript() {
            // e.preventDefualt;
            console.log("asda");
        }
    </script>




</body>

Views/Token/listof.cshtml
@model WebApplication3.ViewModels.TokenViews

@{
    ViewBag.Title = "listof";
}

<h2>listof</h2>
@Html.AntiForgeryToken()
@foreach (var item in Model.tok)
{
    <div>
        <h6> @item</h6>
    </div>

}